### PR TITLE
Update sbt-web and sbt versions

### PR DESCRIPTION
**Pull request by richdougherty**
Updated to latest sbt-web version, see: https://github.com/playframework/playframework/issues/7045#issuecomment-303180324.

Something to consider in a future update is to use the `sbt-web-build-base` plugin to bring in a lot of standard sbt-web build configuration. See: https://github.com/sbt/sbt-mocha/pull/20/files#diff-a84f91f20f040218bccd09fed4761fb3

### CODE REVIEW

**Comment by richdougherty** [comment]
Thanks @irundaia! Any chance of a release? We're trying up get new releases out for popular sbt-web plugins.

**Comment by irundaia** [comment]
You're welcome! I was hoping to update libsass to version 3.4.5 first. But I'm having some issues with building the linux 64bit version. I hope to release it this week though.

**Comment by richdougherty** [comment]
OK thanks!


-- 
Rich Dougherty
*Engineer, Lightbend, Inc*
@richdougherty <https://twitter.com/richdougherty>

**Comment by irundaia** [comment]
Just an update: I've built the binaries for libsass 3.4.5. But there seems to be something wrong with the publishing mechanism to bintray. I'll try to debug the publish mechanism this evening.

**Comment by richdougherty** [comment]
OK, good luck!

**Comment by richdougherty** [comment]
@irundaia, how'd you go with the release? I'm just going to publish sbt-jshint, then I thought I might announce the updates. I can include sbt-sassify in the announcement if it's ready. :)

**Comment by irundaia** [comment]
@richdougherty I released sbt-sassify somewhere last week. You're welcome to include version 1.4.9 in your announcement :)

**Comment by richdougherty** [comment]
Thanks 👍

**Pull request merged**
