### PR TITLE
updating dependencies

### PR DESCRIPTION
**Pull request by yurique**

### CODE REVIEW

**Comment by irundaia** [comment]
LGTM. Not sure whether this warrants a new release though.

**Comment by yurique** [comment]
Great! :)

I had to make these changes and `publish-local` it because of this weird error that I was getting (all builds failing) when doing `sbt web-assets:sassify`:

```
[trace] Stack trace suppressed: run last backend/web-assets:sassify for the full output.
[error] (backend/web-assets:sassify) java.lang.NoSuchMethodError: com.typesafe.sbt.web.CompileProblems$.report(Lsbt/LoggerReporter;Lscala/collection/Seq;)V
[error] Total time: 9 s, completed Aug 31, 2017 9:09:59 AM
> last backend/web-assets:sassify
java.lang.NoSuchMethodError: com.typesafe.sbt.web.CompileProblems$.report(Lsbt/LoggerReporter;Lscala/collection/Seq;)V
	at org.irundaia.sbt.sass.SbtSassify$$anonfun$7$$anonfun$9.apply(SbtSassify.scala:116)
	at org.irundaia.sbt.sass.SbtSassify$$anonfun$7$$anonfun$9.apply(SbtSassify.scala:85)
	at com.typesafe.sbt.web.incremental.package$.syncIncremental(package.scala:228)
	at org.irundaia.sbt.sass.SbtSassify$$anonfun$7.apply(SbtSassify.scala:133)
	at org.irundaia.sbt.sass.SbtSassify$$anonfun$7.apply(SbtSassify.scala:67)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Tried `sbt clean`, removed all `target` dirs, even cleaned ivy and coursier cache, and all `target`s under `~/sbt`, tried running sbt with coursier and with default resolver - no luck.

And I don't really know what caused it - it used to work just fine some time ago. Back then I had this:
```
addSbtPlugin("com.typesafe.sbt" % "sbt-web" % "1.4.0")
```
now this:
```
addSbtPlugin("com.typesafe.sbt" % "sbt-web" % "1.4.2")
```
but that doesn't seem to be the reason - it fails now even if I revert it.

I also tried to `publish-local` the 1.4.9 code (under different version, like 1.4.9.1) - no luck with any of sbt-web 1.4.0, 1.4.1, 1.4.2.

Only after I applied changes in this PR and `publish-local`ed it - it started to work. Probably something got messed up on my machine, but I have no idea what else to clean :)

**Comment by yurique** [comment]
And one more thing I faced - if I have Artima Supersafe plugin enabled, I get this:
```
[info] Set current project to sbt-sassify (in build file:/home/yurique/git/yurique/sbt-sassify/)
> compile
[warn] Credentials file /home/yurique/.bintray/.credentials does not exist, ignoring it
[warn] Credentials file /home/yurique/.bintray/.credentials does not exist, ignoring it
[info] Compiling 12 Scala sources and 2 Java sources to /home/yurique/git/yurique/sbt-sassify/target/sbt-0.13/classes...
[info] Artima SuperSafe(TM) 1.1.2 activated (licensed to Iurii Malchenko, expires on 01 Mar 2018). Copyright (C) 2015 Artima, Inc. All Rights Reserved.
[success] Total time: 5 s, completed Aug 31, 2017 9:33:35 AM

> publish-local
[warn] Credentials file /home/yurique/.bintray/.credentials does not exist, ignoring it
[warn] Credentials file /home/yurique/.bintray/.credentials does not exist
[info] Writing Ivy file /home/yurique/git/yurique/sbt-sassify/target/resolution-cache/org.irundaia.sbt/sbt-sassify/scala_2.10/sbt_0.13/1.4.9.2-SNAPSHOT/resolved.xml.xml
[warn] Credentials file /home/yurique/.bintray/.credentials does not exist, ignoring it
[info] :: delivering :: org.irundaia.sbt#sbt-sassify;1.4.9.2-SNAPSHOT :: 1.4.9.2-SNAPSHOT :: release :: Thu Aug 31 09:33:38 EEST 2017
[info] 	delivering ivy file to /home/yurique/git/yurique/sbt-sassify/target/sbt-0.13/ivy-1.4.9.2-SNAPSHOT.xml
[info] Main Scala API documentation to /home/yurique/git/yurique/sbt-sassify/target/sbt-0.13/api...
[info] Packaging /home/yurique/git/yurique/sbt-sassify/target/sbt-0.13/sbt-sassify-1.4.9.2-SNAPSHOT.jar ...
[info] Artima SuperSafe(TM) 1.1.2 activated (licensed to Iurii Malchenko, expires on 01 Mar 2018). Copyright (C) 2015 Artima, Inc. All Rights Reserved.
[error] dropping dependency on node with no phase object: refchecks
[info] No documentation generated with unsucessful compiler run
[error] one error found
[info] Done packaging.
[error] (compile:doc) Scaladoc generation failed
[error] Total time: 1 s, completed Aug 31, 2017 9:33:39 AM
```

**Comment by adridadou** [comment]
I have the same issue. Would it be possible to have a new release for that ?

**Pull request merged**
